include: package:flutter_lints/flutter.yaml

analyzer:
    exclude: [lib/*.*.dart, lib/**/*.*.dart, test/**/*.*.dart,lib/generated_plugin_registrant.dart]

linter:
  rules:
    - use_build_context_synchronously
    - always_declare_return_types
    - annotate_overrides
    - avoid_field_initializers_in_const_classes
    - avoid_redundant_argument_values
    - avoid_escaping_inner_quotes
    - avoid_empty_else
    - avoid_returning_null_for_void
    - avoid_returning_null_for_future
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - deprecated_consistency
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - no_logic_in_create_state
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_void_to_null
    - sized_box_for_whitespace
    - sort_child_properties_last
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_if_null_to_convert_nulls_to_bools
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - use_setters_to_change_properties