name: mani_mate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  circular_menu: ^2.0.1
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  flutter_animate: ^4.1.1+1
  flutter_local_notifications: ^14.1.1
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  infinite_carousel: ^1.0.3
  intl: ^0.18.0
  riverpod_annotation: ^2.1.1
  scrollable_positioned_list: ^0.3.8
  syncfusion_flutter_datepicker: ^21.2.10
  uuid: ^3.0.6
  unixtime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.1.4
  hive_generator: ^2.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
